apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
  - name: replacer.agb.dev
    sideEffects: None
    failurePolicy: Fail
    admissionReviewVersions: ["v1"]
    objectSelector:
      matchExpressions:
        - key: part-of
          operator: NotIn
          values:
            - replacer
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
          - kube-public
          - kube-node-lease
          - replacer
    clientConfig:
      service:
        name: webhook-service
        namespace: replacer
        path: /replace
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - secrets
          - secrets/*
          - configmaps
